# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: GitHub520

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then sudo pip install -r requirements.txt; fi
    - name: Test connectivity to api.github.com
      run: |
        echo "api.github.com"
        curl -I https://api.github.com
        echo "assets-cdn.github.com"
        curl -I https://assets-cdn.github.com
        echo "avatars.githubusercontent.com"
        curl -I https://avatars.githubusercontent.com
        echo "yml的python单独测试网络开始"
        python -c "import socket; print(socket.gethostbyname('api.github.com'))"
        python -c "import socket; print(socket.gethostbyname('assets-cdn.github.com'))"
        python -c "import socket; print(socket.gethostbyname('avatars.githubusercontent.com'))"
        echo "yml的python单独测试结束"
    - name: run script
      run: |
        # fetch new ip content and update readme file
        sudo python fetch_ips.py
    - name: commit
      id: commit
      run: |
        ls -la
        pwd
        git config --global user.email action@github.com
        git config --global user.name GitHub Action
        git add .
        git status
        git commit -m "update readme content" || echo "No changes to commit"
        git push origin main
      continue-on-error: false
    - name: Check on failures
      if: steps.commit.outputs.status == 'failure'
      run: |
        echo 'steps.commit.outputs.status == failure'
        exit 1
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}


